package com.nexit.app;
import android.app.NotificationChannel;import android.app.NotificationManager;import android.app.PendingIntent;import android.content.BroadcastReceiver;import android.content.Context;import android.content.Intent;import android.media.AudioAttributes;import android.os.Build;import android.provider.Settings;import androidx.core.app.NotificationCompat;
public class AlarmReceiver extends BroadcastReceiver{
 private static final String CHANNEL="nexit_alarm";
 @Override public void onReceive(Context c,Intent intent){String day=intent==null?"lunes":intent.getStringExtra("targetDay");boolean diagnostic=intent!=null&&intent.getBooleanExtra("diagnostic",false);String body=diagnostic?"Prueba nativa correcta. Android ha disparado la alarma local de Nexit.":"Toca para abrir la preparación de "+label(day)+".";show(c,body,day);String json=c.getSharedPreferences("nexit",Context.MODE_PRIVATE).getString("state","");if(!json.isEmpty())AlarmScheduler.scheduleAll(c,json);}
 private void show(Context c,String body,String day){createChannel(c);Intent open=new Intent(c,MainActivity.class).putExtra("reminderDay",day).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent pi=PendingIntent.getActivity(c,777,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);NotificationCompat.Builder b=new NotificationCompat.Builder(c,CHANNEL).setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle("Nexit").setContentText(body).setCategory(NotificationCompat.CATEGORY_ALARM).setPriority(NotificationCompat.PRIORITY_MAX).setAutoCancel(true).setContentIntent(pi).setFullScreenIntent(pi,true);((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).notify((int)(System.currentTimeMillis()%100000),b.build());}
 private void createChannel(Context c){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL,"Alarmas de Nexit",NotificationManager.IMPORTANCE_HIGH);ch.enableVibration(true);ch.setSound(Settings.System.DEFAULT_ALARM_ALERT_URI,new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).build());((NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).createNotificationChannel(ch);}}
 private String label(String d){if(d==null)return"hoy";switch(d){case"miercoles":return"miércoles";case"sabado":return"sábado";default:return d;}}
}
