package com.nexit.app;
import android.app.AlarmManager;import android.app.PendingIntent;import android.content.Context;import android.content.Intent;import android.os.Build;import org.json.JSONArray;import org.json.JSONObject;import java.time.Instant;import java.util.Calendar;
public final class AlarmScheduler{
 private AlarmScheduler(){}
 public static final class Result{public int scheduled=0;public String error="";}
 public static Result scheduleAll(Context c,String json){Result r=new Result();try{JSONObject root=new JSONObject(json);JSONObject settings=root.getJSONObject("settings");boolean enabled=settings.optBoolean("appEnabled",true)&&settings.optBoolean("alarmsEnabled",true);JSONArray schedules=root.getJSONArray("schedules");AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);for(int i=0;i<7;i++){am.cancel(pending(c,3100+i,"",false));am.cancel(pending(c,3200+i,"",false));}am.cancel(pending(c,3999,"",true));if(!enabled)return r;for(int i=0;i<schedules.length();i++){JSONObject s=schedules.getJSONObject(i);String day=s.optString("showOnDay",s.optString("targetDay","lunes"));String target=s.optString("targetDay",day);String[] hm=s.optString("showAt","06:00").split(":");int h=Integer.parseInt(hm[0]),m=Integer.parseInt(hm[1]);long when=next(dayIndex(day),h,m);set(c,am,when,pending(c,3100+i,target,false));r.scheduled++;}
 JSONArray states=root.optJSONArray("dayStates");if(states!=null){for(int i=0;i<states.length();i++){JSONObject st=states.getJSONObject(i);String iso=st.optString("snoozedUntil","");if(iso.isEmpty())continue;try{long when=Instant.parse(iso).toEpochMilli();if(when>System.currentTimeMillis()){set(c,am,when,pending(c,3200+i,st.optString("targetDay","lunes"),false));r.scheduled++;}}catch(Exception ignored){}}}
 }catch(Exception e){r.error=e.getClass().getSimpleName()+":"+(e.getMessage()==null?"":e.getMessage());}return r;}
 private static void set(Context c,AlarmManager am,long when,PendingIntent pi){boolean exact=Build.VERSION.SDK_INT<31||am.canScheduleExactAlarms();if(exact)am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,pi);else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,when,pi);}
 public static boolean scheduleDiagnostic(Context c,long delay){try{AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);set(c,am,System.currentTimeMillis()+delay,pending(c,3999,"lunes",true));return true;}catch(Exception e){return false;}}
 private static PendingIntent pending(Context c,int code,String target,boolean diagnostic){Intent i=new Intent(c,AlarmReceiver.class).setAction("NEXIT_ALARM_"+code).putExtra("targetDay",target).putExtra("diagnostic",diagnostic);return PendingIntent.getBroadcast(c,code,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 private static int dayIndex(String d){String[] a={"lunes","martes","miercoles","jueves","viernes","sabado","domingo"};for(int i=0;i<a.length;i++)if(a[i].equals(d))return i;return 0;}
 private static long next(int mondayIndex,int h,int m){Calendar now=Calendar.getInstance(),x=Calendar.getInstance();x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,m);x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);int target=((mondayIndex+1)%7)+1;int add=(target-now.get(Calendar.DAY_OF_WEEK)+7)%7;x.add(Calendar.DAY_OF_YEAR,add);if(x.getTimeInMillis()<=now.getTimeInMillis())x.add(Calendar.DAY_OF_YEAR,7);return x.getTimeInMillis();}
}
